# Generated by Django 5.2.6 on 2025-09-09 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del puesto')),
                ('description', models.TextField(verbose_name='Descripción del puesto')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('job_type', models.CharField(choices=[('full_time', 'Tiempo completo'), ('part_time', 'Tiempo parcial'), ('contract', 'Contrato'), ('internship', 'Prácticas'), ('freelance', 'Freelance')], max_length=20, verbose_name='Tipo de trabajo')),
                ('experience_level', models.CharField(choices=[('entry', 'Nivel de entrada'), ('junior', 'Junior'), ('mid', 'Intermedio'), ('senior', 'Senior'), ('executive', 'Ejecutivo')], max_length=20, verbose_name='Nivel de experiencia')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salario mínimo')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salario máximo')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Moneda')),
                ('remote_work', models.BooleanField(default=False, verbose_name='Trabajo remoto')),
                ('skills_required', models.TextField(blank=True, help_text='Separar con comas', verbose_name='Habilidades requeridas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'Oferta de trabajo',
                'verbose_name_plural': 'Ofertas de trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Carta de presentación')),
                ('status', models.CharField(choices=[('applied', 'Aplicado'), ('reviewing', 'En revisión'), ('interview', 'Entrevista'), ('rejected', 'Rechazado'), ('accepted', 'Aceptado')], default='applied', max_length=20, verbose_name='Estado')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de aplicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del empleador')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Candidato')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='Oferta de trabajo')),
            ],
            options={
                'verbose_name': 'Aplicación de trabajo',
                'verbose_name_plural': 'Aplicaciones de trabajo',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
