# Generated by Django 5.2.6 on 2025-09-09 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('job_seeker', 'Buscador de empleo'), ('employer', 'Empleador')], max_length=20, verbose_name='Tipo de usuario')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='CV')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de perfil')),
                ('skills', models.TextField(blank=True, help_text='Separar con comas', verbose_name='Habilidades')),
                ('experience_years', models.IntegerField(blank=True, null=True, verbose_name='Años de experiencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
